"""add messages table

Revision ID: 3ce875da921a
Revises: b1234567890a
Create Date: 2026-06-17 00:09:44.749628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce875da921a'
down_revision = 'b1234567890a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reset_expiration', sa.DateTime(), nullable=True))
        batch_op.alter_column('avatar_config',
               existing_type=sa.VARCHAR(length=512),
               nullable=False,
               existing_server_default=sa.text('\'{" body:\\#2196F3\\,\x07rms:\\#4CAF50\\,\\legs:\\#FFC107\\}\''))
        batch_op.create_unique_constraint(None, ['unique_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('avatar_config',
               existing_type=sa.VARCHAR(length=512),
               nullable=True,
               existing_server_default=sa.text('\'{" body:\\#2196F3\\,\x07rms:\\#4CAF50\\,\\legs:\\#FFC107\\}\''))
        batch_op.drop_column('reset_expiration')
        batch_op.drop_column('reset_code')

    op.drop_table('messages')
    # ### end Alembic commands ###
