"""Add language to User

Revision ID: c66ac5f0cb15
Revises: c36af4789413
Create Date: 2026-05-31 14:03:09.197013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66ac5f0cb15'
down_revision = 'c36af4789413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=2), nullable=False))
        batch_op.create_unique_constraint(None, ['unique_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
